### ISSUE TITLE
3 of me at https://ncsu.software/services/researchers/

### ISSUE THREAD

**Issue by maxxbw54** [ncsu-software/ncsu-software.github.io#25]
At the beginning, I filled the form (FORM #1) [https://forms.gle/37bgNp78hXGuewkj7](https://forms.gle/37bgNp78hXGuewkj7) when @timm first time invited us. (I forgot which email I used to fill the form)

And then, I try to update my info. So from [https://github.com/ncsu-software/ncsu-software.github.io/tree/main#forms](https://github.com/ncsu-software/ncsu-software.github.io/tree/main#forms), I filled the Researchers form (FORM #2): [Click here to access the form](https://forms.gle/72LCSdHEs63TW8HX7) 2 times (by using my NCSU email).

Now, I find there are 3 me at https://ncsu.software/services/researchers.

Q1:
How can I delete the redundant ones?

Q2:
What is the unique identifier to update?

Q3:
FORM #1 and #2 are different. Only FORM #1 requires the info about Lab while FORM #2 seems more recent. Which one shall I use?

Pls correct me if I do anything wrong for info update purpose. 

Thanks for the great effort on our team website!  @timm @nagarajumadamshetti

**Comment by nagarajumadamshetti** [comment]
please submit your responses with ncsu email; Once you submit any form, you'll receive the responses to your email; So in the future if you want to update the information, you could just go to that email with form response, and click on it to go ahead and update the previous response;

In case you want to submit multiple entries in a form such as news, you just have to submit it multiple times;

Answer 1: You cant delete the redundant ones unless you have access to google sheets;
Answer2: the unique identifier is the email address;
Answer3: I believe you can discard the form that we sent you first time; So now you can just submit the data on the forms listed on the readme
